baseURL = "https://bbstk.github.io/website/"
languageCode = "en-us"
title = "Ivan's website"
theme = "purehugo"
Paginate = 10
publishDir = "../docs"

[params]
  githubName = "bbstk"
  description = "A place for my thoughts, projects, experiments..."

